#:schema node_modules/wrangler/config-schema.json
name = "dingyue"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "da13f1f4d7b84e408c060bf5948a0b1d" }
]

[assets]
directory = "./public"
